### ISSUE TITLE
Brewery Inheritance for Uses

### ISSUE THREAD

**Issue by iosru** [Swedz/Extended-Industrialization#4]
Steel Brewery and Electric Brewery need inheritance from the vanilla Brewing Stand for uses.

**Comment by MuteTiefling** [comment]
Would very much appreciate this as well so it shows as an option for brewing when people are looking at the potions

**Comment by Swedz** [comment]
I do want to add this. I'm not exactly happy with how the brewery works right now, and I want to at some point redo it to use actual recipes instead of faked recipes like the brewing stand in vanilla works. There'd be some functional changes in how the brewery would work if I did that too. I want it to be more inline with how machines work in MI instead of being this thing that can do multiple steps of recipes in one. Modded potions would need to have their recipes added to the brewery as well, but it would give modpack creators a bit more control over the brewery machine. I really wish mojang would just redo potions and make them use actual json recipes like everything else in the game lol

**Comment by Swedz** [comment]
Added in 1.5.0+1.21
