### ISSUE TITLE
Steam Chainsaw causes client crash loop when cutting large trees on 1.21.1

### ISSUE THREAD

**Issue by rruy-dev** [Swedz/Extended-Industrialization#81]
While cutting redwood trees (very large) using the Steam Chainsaw, players are getting disconnected with their clients crashing, and are unable to rejoin the server until their playerdata is edited to remove it from their inventory.

### Details
ATM10 v2.6, latest release as of writing
Neoforge 21.1.90 Server
Extended Industrialization v1.10.0-beta-1.21.1, latest release as of writing

Crash Log
https://mclo.gs/H8m7FmJ

**Comment by James103** [comment]
A `NullPointerException` is being thrown here because once the Steam Chainsaw's water level reaches 0, the component is cleared and the next tick its water level is tried to be decremented, it fails to find the water level component and crashes.
Possible solution: Replace the `stack.get(MIComponents.WATER)` call with `stack.getOrDefault(MIComponents.WATER, 0)`.
https://github.com/Swedz/Extended-Industrialization/blob/b69d88dbd64174dc2f8676fdf3139e6d50c7ce95/src/main/java/net/swedz/extended_industrialization/item/SteamChainsawItem.java#L259

To reproduce: let a Steam Chainsaw run until its water level reaches 0 with fuel left to burn.

**Comment by Swedz** [comment]
A better solution is to use `ItemStack#update`
